algoritmo "Combinacoes"

var
   Contador1, Contador2, Contador3, Contador4: Inteiro
inicio
      Para Contador1 := 1 ate 5 faca
           Para Contador2 := 1 ate 5 faca
                Para Contador3 := 1 ate 5 faca
                     Para Contador4 := 1 ate 5 faca
                          EscrevaL (Contador1, Contador2, Contador3, Contador4)
                     FimPara
                FimPara
           FimPara
      FimPara

fimalgoritmo
